# Generated by Django 5.1.4 on 2024-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizza(s)'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Size(s)'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
