# Generated by Django 5.1.4 on 2024-12-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizza_options_alter_size_options_pizza_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='email',
        ),
    ]
